### PR TITLE
Fex spullng

### PR DESCRIPTION
**Pull request by addisoncrump**
(Nineteenth Byte strikes again)

### CODE REVIEW

**Comment by vihanb** [comment]
ಠ_ಠ

**Comment by vihanb** [comment]
wait wat did I just do

**Comment by addisoncrump** [comment]
xD Wul dun

**Comment by vihanb** [comment]
:|

**Comment by addisoncrump** [comment]
git rekt

**Comment by vihanb** [comment]
oh no, how do I [revert a commit](https://github.com/vihanb/PPCG-Design/commit/8bdadd03c7937ed250e35506cf0412fb3cd151d6)

**Comment by vihanb** [comment]
I just [auto updated](https://github.com/vihanb/PPCG-Design/commit/8bdadd03c7937ed250e35506cf0412fb3cd151d6) for the high resolution stars to take place and forgot about this

**Comment by schas002** [comment]
You cannot revert a merged pull request. Never. If you want, I can request to pull a "misspell it back" commit. More information on merging pull requests: [help center](https://help.github.com/articles/merging-a-pull-request/).

**Comment by RikerW** [comment]
rofl

**Pull request merged**
