### PR TITLE
Add a question of the day panel

### PR DESCRIPTION
**Pull request by JJ-Atkinson**
Add a question of the day panel to the right hand side with the other widgets. This gets random questions with a score >7 and older than a year by tags. The top 3 tags are set to `code-golf`, `KOTH`, and `fastest-code`. The other 2 tags are rotated daily and are from the first page of tags by popularity. Somewhat based on http://meta.codegolf.stackexchange.com/a/8068/42736.

image

### CODE REVIEW

**Comment by vihanb** [comment]
That is awesome. One bug is that the &lt;div> with the code-golf favicons have a title of `Unix & Linux Stack Exchange`

**Comment by JJ-Atkinson** [comment]
Oh, hehe ;) I was working out how to get the favicon beside the question, and I used the HNQ as an example. That does remind me that this has one other bug. If a question has a `'` in it, everything after it is discarded and you can only see the part before the `'`. I don't know how to fix this, but I don't think that the cookies are broken because when I check them the whole title is there...

**Comment by vihanb** [comment]
I think this can be fixed by replacing the `'` with a `&apos;`. I'll be on it...

**Comment by JJ-Atkinson** [comment]
Thanks

**Comment by vihanb** [comment]
The script also has an API key: `DwnkTjZvdT0qLs*o8rNDWw((` which you can use to get a higher req/day (~10,000)

**Comment by JJ-Atkinson** [comment]
That's good, I was wondering if I would ever hit the limit, though I have been using this for ~3 weeks without hitting it.

**Comment by JJ-Atkinson** [comment]
I think the SE sites have their own quota of ~300 per day. Side note: Does the 10k limit apply to all the users of this script?

**Pull request merged**
