### PR TITLE
Fix #73

### LINKED ISSUE #73: Try it online result doesn't work
[Example](http://codegolf.stackexchange.com/a/77021/45941)

What it shows:

[Actual output](http://seriously.tryitonline.net/#code=LFJwQM61alNAJCs&input=MTI)

### PR DESCRIPTION
**Pull request by Mego**
Dead simple, why didn't you do this months ago?

### CODE REVIEW

**Comment by Mego** [comment]
I told you it was the userscript's fault.

**Comment by vihanb** [comment]
Can you increment the version number so when I merge it'll auto-update?

**Comment by ETHproductions** [comment]
Can we just merge and increment the version number manually?

**Comment by ETHproductions** [comment]
Made these changes in e12f6cd.

**Pull request closed without merging**
