### PR TITLE
Update to make QOD items not duplicate

### LINKED ISSUE #104: Duplicate entries in challenge of the day
image

### PR DESCRIPTION
**Pull request by JJ-Atkinson**
Also fixes a slight bug in the settings pane, and adds a new setting to show/hide the QOD widget. This breaks Edge and FF compatibility. Need help to fix it. Seems to be a timeout in the new code. Would fix #104

### CODE REVIEW

**Comment by ETHproductions** [comment]
I don't see any problems in Firefox 50. What exactly is going wrong?

**Comment by JJ-Atkinson** [comment]
@ETHproductions It seems to have something to do with `getOtherTags` on FF at least. I'm using Firefox 51 on windows 10. Here are some recordings:

With fix:

capture

Without:

capture2

I assume the same is true for edge.

**Comment by ETHproductions** [comment]
The only thing I can think of right now is if there's two tags missing when line 1013 is run, and thus it tries repeatedly but unsuccessfully to add them in. Is that a possibility?

**Comment by JJ-Atkinson** [comment]
I'll check into this more tomorrow, but I think that I add the attempted item is _always_ in the list, because it is added before it is validated! Sometimes I feel real stupid. But since it works on some browsers, I'm mystified.

**Comment by JJ-Atkinson** [comment]
It _does_ hang on all browsers! It didn't yesterday because it had already chose QOD content and didn't run code. Today it did while getting the new questions.

**Comment by ETHproductions** [comment]
Dangit, you're right, and I think I was right too... The first tag appears to keep cycling through its options forever.

**Pull request merged**
