### PR TITLE
¯\_(ツ)_/¯ 

### PR DESCRIPTION
**Pull request by vihanb**
http://strawpoll.me/6847681/r

### CODE REVIEW

**Comment by vihanb** [comment]
I'm sorry

**Comment by addisoncrump** [comment]
`s/propose/porpoise` lel rekt gg @Mego

**Comment by Mego** [comment]
_this is stupid and looks stupid_

**Comment by RikerW** [comment]
True.
 Maybe a config option?  Like in the setting menu.

**Comment by vihanb** [comment]
If you really hate porpoising questions you can always modify the script from TamperMonkey/GreaseMonkey

**Pull request merged**
