### PR TITLE
a whole lot of changes

### PR DESCRIPTION
**Pull request by molarmanful**
- Style background
- Style buttons
- Finish up links
- Fix bounty color
- Fix regex for byte counter (APL was matching for Maple)
- Style mod flair diamond
- Other changes that I'm probably forgetting

### CODE REVIEW

**Comment by molarmanful** [comment]
NOTE: The background changes may interfere with some user settings. Perhaps this could be fixed in a later commit.

**Comment by vihanb** [comment]
Cool, I'll take a look at the changes and then merge them. About the background changes, it's been decided that we'll just have a background header to avoid too much green.

**Comment by molarmanful** [comment]
Oh I see... Didn't know that. Personally, I find it okay, but that's just me.

**Comment by molarmanful** [comment]
So, what's the update on this?

**Comment by vihanb** [comment]
Ah, yes, sorry, forgot about this, I'll merge the changes and get back to you in ~15 minutes. I'll also integrate it with the Customizable object. Not a fan of _all_ the links being green. I think it's too much...

**Comment by vihanb** [comment]
I've merged the changes. I haven't added the background changes, I'll add it with an option to toggle it some other time.

**Pull request closed without merging**
